### ISSUE TITLE
error in running NeuralParscit 

### ISSUE THREAD

**Issue by bvgaurav4** [WING-NUS/sciwing#5]
hyperparams.json not found where can i get it ,
if i am doing somthing wrong pls correct me .

**Comment by knmnyn** [comment]
Hi @bvgaurav4: @abhinavkashyap may be able to assist in this matter, but he has graduated and we no longer directly support this toolkit.  You may want to try our newer system SciAssist:

https://github.com/WING-NUS/SciAssist

https://huggingface.co/spaces/wing-nus/SciAssist (see 2nd tab)

**Comment by bvgaurav4** [comment]
Thank you for your email, i have another question can SCIAssist extract
citation context for all the citations?
srry for disturbing and thank you
